# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target "BRAFeatureFlagController" do
  pod "BRAFeatureFlagController", :path => "../"
end

target "BRAFeatureFlagControllerTests" do
  pod 'Kiwi'
end

